"""
Audit Report Builder

Generate structured audit reports in multiple formats.
"""

from typing import Dict, Any, List
from enum import Enum
import json


class AuditReportFormat(Enum):
    """Report output formats"""
    JSON = "json"
    MARKDOWN = "markdown"
    HTML = "html"
    TEXT = "text"


def build_audit_report(
    audit_results: Dict[str, Any],
    format: AuditReportFormat = AuditReportFormat.MARKDOWN
) -> str:
    """
    Build formatted audit report.
    
    Args:
        audit_results: Dictionary of audit findings
        format: Output format
    
    Returns:
        Formatted report string
    """
    if format == AuditReportFormat.JSON:
        return json.dumps(audit_results, indent=2)
    
    elif format == AuditReportFormat.MARKDOWN:
        return _build_markdown_report(audit_results)
    
    elif format == AuditReportFormat.TEXT:
        return _build_text_report(audit_results)
    
    else:
        return _build_markdown_report(audit_results)


def _build_markdown_report(results: Dict[str, Any]) -> str:
    """Build markdown audit report"""
    
    lines = []
    lines.append("# Meridian Strategy Audit Report\n")
    lines.append(f"**Strategy:** {results.get('strategy_name', 'Unknown')}")
    lines.append(f"**Audit ID:** {results.get('audit_id', 'N/A')}")
    lines.append(f"**Timestamp:** {results.get('timestamp', 'N/A')}")
    lines.append(f"**Model:** {results.get('model_used', 'N/A')}")
    lines.append(f"**Confidence:** {results.get('confidence_score', 0):.1f}/100\n")
    lines.append("---\n")
    
    # Summary
    lines.append("## Executive Summary\n")
    lines.append(f"{results.get('summary', 'No summary available')}\n")
    lines.append("---\n")
    
    # Findings
    findings = results.get('findings', {})
    
    if 'strengths' in findings and findings['strengths']:
        lines.append("## ✅ Strengths\n")
        for strength in findings['strengths']:
            lines.append(f"- {strength}")
        lines.append("\n")
    
    if 'weaknesses' in findings and findings['weaknesses']:
        lines.append("## ⚠️  Weaknesses\n")
        for weakness in findings['weaknesses']:
            lines.append(f"- {weakness}")
        lines.append("\n")
    
    if 'gaps' in findings and findings['gaps']:
        lines.append("## 📋 Gaps\n")
        for gap in findings['gaps']:
            lines.append(f"- {gap}")
        lines.append("\n")
    
    # Risk flags
    if results.get('risk_flags'):
        lines.append("## 🚨 Risk Flags\n")
        for flag in results['risk_flags']:
            lines.append(f"- {flag}")
        lines.append("\n")
    
    lines.append("---\n")
    lines.append("*Generated by Meridian Audit Engine (Phase X)*\n")
    
    return '\n'.join(lines)


def _build_text_report(results: Dict[str, Any]) -> str:
    """Build plain text audit report"""
    
    lines = []
    lines.append("=" * 70)
    lines.append("MERIDIAN STRATEGY AUDIT REPORT")
    lines.append("=" * 70)
    lines.append(f"Strategy: {results.get('strategy_name', 'Unknown')}")
    lines.append(f"Confidence: {results.get('confidence_score', 0):.1f}/100")
    lines.append(f"Timestamp: {results.get('timestamp', 'N/A')}")
    lines.append("=" * 70)
    lines.append("")
    lines.append(results.get('summary', 'No summary'))
    lines.append("")
    
    # Risk flags
    if results.get('risk_flags'):
        lines.append("RISK FLAGS:")
        for flag in results['risk_flags']:
            lines.append(f"  - {flag}")
    
    return '\n'.join(lines)

